### ISSUE TITLE
Release faraday changes in PR #67 

### ISSUE THREAD

**Issue by ipavlushin** [mackerelio/mackerel-client-ruby#69]
PR #67 fixes version conflict with other plugins that use a newer version of Faraday. But these changes were not released properly and mackerel-client in [rubygems](https://rubygems.org/gems/mackerel-client) has version 0.12.0 which stipulates [faraday](https://rubygems.org/gems/faraday) ~> 1.0.
@inommm could you push a new version to the rubygems?

**Comment by azukiazusa1** [comment]
Hi, @ipavlushin 

Thanks for letting us know about the issue. We have released mackerel-client-ruby v0.12.1.

https://rubygems.org/gems/mackerel-client/versions/0.12.1

Sorry for the inconvenience.
